name: Deploy Website

on:
  issues: 
    types: [opened, edited, deleted, closed, reopened, labeled, unlabeled, milestoned, demilestoned]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - env: 
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT
          echo $GITHUB_REPOSITORY_OWNER
          echo ${GITHUB_REF##*/}
          echo $USERS
          echo $BRANCH
        
      - name: condition 1
        if: contains(env.USERS, github.event.sender.login)
        run: echo 11

      - name: condition 2
        if: contains('11', github.event.sender.login)
        run: echo 22
      
    # - name: Checkout repository
    #   uses: actions/checkout@v2

    # - name: Set up Node.js
    #   uses: actions/setup-node@v1
    #   with:
    #     node-version: ${{ matrix.node-version }}

    # - name: Install dependencies
    #   run: npm install

    # - name: Run tests
    #   run: npm run test
